# Generated by Django 3.2.14 on 2022-07-26 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=40, verbose_name='竞聘岗位')),
                ('num', models.IntegerField(default=1, verbose_name='职数')),
            ],
            options={
                'verbose_name': '竞聘岗位',
                'verbose_name_plural': '竞聘岗位',
            },
        ),
        migrations.CreateModel(
            name='QuesObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.post', verbose_name='竞聘岗位')),
            ],
            options={
                'verbose_name': '测评对象',
                'verbose_name_plural': '测评对象',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, verbose_name='测评表名')),
                ('is_true', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否可用')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测评时间')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='测评时长')),
                ('obj', models.ManyToManyField(to='compete.QuesObj', verbose_name='测评对象( 按住 Ctrl 键或 Shift 键来选择多项 )')),
            ],
            options={
                'verbose_name': '民主测评表',
                'verbose_name_plural': '民主测评表',
            },
        ),
    ]
