# Generated by Django 3.2.14 on 2022-07-26 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('user', models.CharField(max_length=40, verbose_name='投票人')),
                ('grade', models.CharField(max_length=40, verbose_name='投票人角色')),
                ('voted', models.CharField(max_length=40, verbose_name='测评意见')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.paper', verbose_name='测评名称')),
            ],
            options={
                'verbose_name': '民主测评_测评记录',
                'verbose_name_plural': '民主测评_测评记录',
            },
        ),
    ]
