# Generated by Django 3.2.14 on 2022-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_comprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('vA', models.IntegerField(default=0, verbose_name='同意')),
                ('vB', models.IntegerField(default=0, verbose_name='不同意')),
                ('vC', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '民主测评_全体',
                'verbose_name_plural': '民主测评_全体',
            },
        ),
        migrations.CreateModel(
            name='CompLeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('vA', models.IntegerField(default=0, verbose_name='同意')),
                ('vB', models.IntegerField(default=0, verbose_name='不同意')),
                ('vC', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '民主测评_台领导',
                'verbose_name_plural': '民主测评_台领导',
            },
        ),
        migrations.CreateModel(
            name='CompMiddle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('vA', models.IntegerField(default=0, verbose_name='同意')),
                ('vB', models.IntegerField(default=0, verbose_name='不同意')),
                ('vC', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '民主测评_中层干部',
                'verbose_name_plural': '民主测评_中层干部',
            },
        ),
        migrations.CreateModel(
            name='CompStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('vA', models.IntegerField(default=0, verbose_name='同意')),
                ('vB', models.IntegerField(default=0, verbose_name='不同意')),
                ('vC', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '民主测评_普通职工',
                'verbose_name_plural': '民主测评_普通职工',
            },
        ),
    ]
