# Generated by Django 3.2.14 on 2022-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_compall_compleader_compmiddle_compstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='compall',
            name='num',
            field=models.CharField(max_length=40, null=True, verbose_name='职数'),
        ),
        migrations.AddField(
            model_name='compall',
            name='post',
            field=models.CharField(max_length=40, null=True, verbose_name='竞聘岗位'),
        ),
        migrations.AddField(
            model_name='compleader',
            name='num',
            field=models.CharField(max_length=40, null=True, verbose_name='职数'),
        ),
        migrations.AddField(
            model_name='compleader',
            name='post',
            field=models.CharField(max_length=40, null=True, verbose_name='竞聘岗位'),
        ),
        migrations.AddField(
            model_name='compmiddle',
            name='num',
            field=models.CharField(max_length=40, null=True, verbose_name='职数'),
        ),
        migrations.AddField(
            model_name='compmiddle',
            name='post',
            field=models.CharField(max_length=40, null=True, verbose_name='竞聘岗位'),
        ),
        migrations.AddField(
            model_name='compstaff',
            name='num',
            field=models.CharField(max_length=40, null=True, verbose_name='职数'),
        ),
        migrations.AddField(
            model_name='compstaff',
            name='post',
            field=models.CharField(max_length=40, null=True, verbose_name='竞聘岗位'),
        ),
    ]
