# Generated by Django 3.2.14 on 2022-07-26 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('score', models.FloatField(verbose_name='得分')),
                ('q1', models.IntegerField(verbose_name='德')),
                ('q2', models.IntegerField(verbose_name='能')),
                ('q3', models.IntegerField(verbose_name='勤')),
                ('q4', models.IntegerField(verbose_name='绩')),
                ('q5', models.IntegerField(verbose_name='学')),
                ('q6', models.IntegerField(verbose_name='廉')),
                ('voted_A', models.IntegerField(default=0, verbose_name='优秀')),
                ('voted_B', models.IntegerField(default=0, verbose_name='合格')),
                ('voted_C', models.IntegerField(default=0, verbose_name='基本合格')),
                ('voted_D', models.IntegerField(default=0, verbose_name='不合格')),
                ('voted_E', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '年度考核_全体',
                'verbose_name_plural': '年度考核_全体',
            },
        ),
        migrations.CreateModel(
            name='AnnualLeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('score', models.FloatField(verbose_name='得分')),
                ('q1', models.IntegerField(verbose_name='德')),
                ('q2', models.IntegerField(verbose_name='能')),
                ('q3', models.IntegerField(verbose_name='勤')),
                ('q4', models.IntegerField(verbose_name='绩')),
                ('q5', models.IntegerField(verbose_name='学')),
                ('q6', models.IntegerField(verbose_name='廉')),
                ('voted_A', models.IntegerField(default=0, verbose_name='优秀')),
                ('voted_B', models.IntegerField(default=0, verbose_name='合格')),
                ('voted_C', models.IntegerField(default=0, verbose_name='基本合格')),
                ('voted_D', models.IntegerField(default=0, verbose_name='不合格')),
                ('voted_E', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '年度考核_台领导',
                'verbose_name_plural': '年度考核_台领导',
            },
        ),
        migrations.CreateModel(
            name='AnnualMiddle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('score', models.FloatField(verbose_name='得分')),
                ('q1', models.IntegerField(verbose_name='德')),
                ('q2', models.IntegerField(verbose_name='能')),
                ('q3', models.IntegerField(verbose_name='勤')),
                ('q4', models.IntegerField(verbose_name='绩')),
                ('q5', models.IntegerField(verbose_name='学')),
                ('q6', models.IntegerField(verbose_name='廉')),
                ('voted_A', models.IntegerField(default=0, verbose_name='优秀')),
                ('voted_B', models.IntegerField(default=0, verbose_name='合格')),
                ('voted_C', models.IntegerField(default=0, verbose_name='基本合格')),
                ('voted_D', models.IntegerField(default=0, verbose_name='不合格')),
                ('voted_E', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '年度考核_中层干部',
                'verbose_name_plural': '年度考核_中层干部',
            },
        ),
        migrations.CreateModel(
            name='AnnualStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, null=True, verbose_name='测评对象')),
                ('score', models.FloatField(verbose_name='得分')),
                ('q1', models.IntegerField(verbose_name='德')),
                ('q2', models.IntegerField(verbose_name='能')),
                ('q3', models.IntegerField(verbose_name='勤')),
                ('q4', models.IntegerField(verbose_name='绩')),
                ('q5', models.IntegerField(verbose_name='学')),
                ('q6', models.IntegerField(verbose_name='廉')),
                ('voted_A', models.IntegerField(default=0, verbose_name='优秀')),
                ('voted_B', models.IntegerField(default=0, verbose_name='合格')),
                ('voted_C', models.IntegerField(default=0, verbose_name='基本合格')),
                ('voted_D', models.IntegerField(default=0, verbose_name='不合格')),
                ('voted_E', models.IntegerField(default=0, verbose_name='弃权')),
            ],
            options={
                'verbose_name': '年度考核_普通职工',
                'verbose_name_plural': '年度考核_普通职工',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evm.department', verbose_name='所在部门')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evm.grade', verbose_name='角色')),
            ],
            options={
                'verbose_name': '测评对象',
                'verbose_name_plural': '测评对象',
            },
        ),
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='测评项')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('e', models.CharField(max_length=40, verbose_name='E选项')),
                ('f', models.CharField(max_length=40, verbose_name='F选项')),
                ('g', models.CharField(max_length=40, verbose_name='G选项')),
                ('h', models.CharField(max_length=40, verbose_name='H选项')),
                ('i', models.CharField(max_length=40, verbose_name='I选项')),
                ('j', models.CharField(max_length=40, verbose_name='J选项')),
            ],
            options={
                'verbose_name': '考评内容',
                'verbose_name_plural': '考评内容',
            },
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='测评项')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('e', models.CharField(max_length=40, verbose_name='E选项')),
            ],
            options={
                'verbose_name': '综合评价',
                'verbose_name_plural': '综合评价',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, verbose_name='测评表名')),
                ('is_true', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否可用')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测评时间')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='测评时长')),
                ('num', models.IntegerField(default=0, null=True, verbose_name='优秀人数')),
                ('obj', models.ManyToManyField(to='annual.Object', verbose_name='测评对象( 按住 Ctrl 键或 Shift 键来选择多项 )')),
            ],
            options={
                'verbose_name': '干部考核表',
                'verbose_name_plural': '干部考核表',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='pid1',
            field=models.ManyToManyField(to='annual.Question1', verbose_name='考评内容( 按住 Ctrl 键或 Shift 键来选择多项 )'),
        ),
        migrations.AddField(
            model_name='object',
            name='pid2',
            field=models.ManyToManyField(to='annual.Question2', verbose_name='综合评价'),
        ),
        migrations.CreateModel(
            name='AnnualRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('user', models.CharField(max_length=40, verbose_name='用户名')),
                ('grade', models.CharField(max_length=40, verbose_name='投票人角色')),
                ('dep', models.CharField(max_length=40, verbose_name='所在部门')),
                ('score', models.FloatField(verbose_name='总分')),
                ('q1', models.IntegerField(verbose_name='德')),
                ('q2', models.IntegerField(verbose_name='能')),
                ('q3', models.IntegerField(verbose_name='勤')),
                ('q4', models.IntegerField(verbose_name='绩')),
                ('q5', models.IntegerField(verbose_name='学')),
                ('q6', models.IntegerField(verbose_name='廉')),
                ('voted', models.CharField(blank=True, max_length=8, verbose_name='综合评价')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annual.testpaper', verbose_name='测评名称')),
            ],
            options={
                'verbose_name': '年度考核_测评记录',
                'verbose_name_plural': '年度考核_测评记录',
            },
        ),
    ]
