# Generated by Django 3.2.14 on 2022-07-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpaper',
            options={'verbose_name': '年度考核表', 'verbose_name_plural': '年度考核表'},
        ),
    ]
