# Generated by Django 3.2.14 on 2022-08-08 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=40, verbose_name='职级')),
            ],
            options={
                'verbose_name': '职级',
                'verbose_name_plural': '职级',
            },
        ),
        migrations.CreateModel(
            name='ReCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper', models.CharField(max_length=40, verbose_name='测评名称')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('post', models.CharField(max_length=40, verbose_name='现工作岗位')),
                ('vl', models.IntegerField(default=0, verbose_name='台领导')),
                ('vm', models.IntegerField(default=0, verbose_name='中层干部')),
                ('vs', models.IntegerField(default=0, verbose_name='普通职工')),
                ('vote', models.IntegerField(default=0, verbose_name='得票数')),
                ('sum', models.IntegerField(default=0, verbose_name='总票数')),
                ('ratio', models.CharField(max_length=40, verbose_name='得票率')),
            ],
            options={
                'verbose_name': '民主推荐统计',
                'verbose_name_plural': '民主推荐统计',
            },
        ),
        migrations.CreateModel(
            name='ReObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('sex', models.BooleanField(blank=True, choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('birth', models.CharField(blank=True, max_length=40, null=True, verbose_name='出生年月')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('work_time', models.CharField(blank=True, max_length=40, null=True, verbose_name='参加工作时间')),
                ('dates', models.CharField(blank=True, max_length=40, null=True, verbose_name='入局时间')),
                ('status', models.CharField(blank=True, max_length=40, null=True, verbose_name='政治面貌')),
                ('post', models.CharField(blank=True, max_length=40, null=True, verbose_name='现任职务')),
                ('time_in_post', models.CharField(blank=True, max_length=40, null=True, verbose_name='任现职时间')),
                ('job_title', models.CharField(blank=True, max_length=40, null=True, verbose_name='专业职务')),
                ('degree', models.CharField(blank=True, max_length=40, null=True, verbose_name='文化程度')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recom.rank', verbose_name='现职级')),
            ],
            options={
                'verbose_name': '测评对象',
                'verbose_name_plural': '测评对象',
            },
        ),
        migrations.CreateModel(
            name='RePaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, verbose_name='测评表名')),
                ('post', models.CharField(max_length=40, verbose_name='岗位名称')),
                ('num', models.IntegerField(default=1, verbose_name='职数')),
                ('is_true', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否可用')),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测评')),
                ('obj', models.ManyToManyField(to='recom.ReObj', verbose_name='测评对象')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recom.rank', verbose_name='职级')),
            ],
            options={
                'verbose_name': '民主推荐表',
                'verbose_name_plural': '民主推荐表',
            },
        ),
        migrations.CreateModel(
            name='ReRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('obj', models.CharField(max_length=40, verbose_name='测评对象')),
                ('user', models.CharField(max_length=40, verbose_name='投票人')),
                ('grade', models.CharField(max_length=40, verbose_name='投票人角色')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recom.repaper', verbose_name='测评名称')),
            ],
            options={
                'verbose_name': '民主推荐_测评记录',
                'verbose_name_plural': '民主推荐_测评记录',
            },
        ),
    ]
