# Generated by Django 3.2.14 on 2022-08-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0002_reobj_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reobj',
            name='test',
        ),
    ]
