# Generated by Django 3.2.14 on 2023-06-15 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0003_remove_reobj_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaper',
            name='c_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='测评时间'),
        ),
    ]
