# Generated by Django 3.2.14 on 2022-07-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssStaff',
            new_name='EmpLeader',
        ),
        migrations.RenameModel(
            old_name='AssMiddle',
            new_name='EmpMiddle',
        ),
        migrations.RenameModel(
            old_name='AssRecord',
            new_name='EmpRecord',
        ),
        migrations.RenameModel(
            old_name='AssLeader',
            new_name='EmpStaff',
        ),
        migrations.AlterModelOptions(
            name='empleader',
            options={'verbose_name': '届满考核_台领导', 'verbose_name_plural': '届满考核_台领导'},
        ),
        migrations.AlterModelOptions(
            name='empstaff',
            options={'verbose_name': '届满考核_普通职工', 'verbose_name_plural': '届满考核_普通职工'},
        ),
    ]
