# Generated by Django 3.2.14 on 2022-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_auto_20220728_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcontent',
            name='detail',
            field=models.CharField(max_length=128, verbose_name='内容'),
        ),
    ]
